name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  scala:
    uses: deed-ie/github-workflows/.github/workflows/scala-deploy-gcp.yml@main
    with:
      SBT_PROJECT_ID: api
      GCP_CLOUD_RUN_SERVICE: property-price-register
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
