name: Continuous Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: deed-ie/github-workflows/.github/workflows/continuous-integration.yml@main
